-- Deprecated compatibility entrypoint.
--
-- Demo users must be created through Supabase Auth so passwords are hashed and
-- profile foreign keys remain valid. The catalog data used by local and staging
-- environments lives in ./seed.sql and is applied through supabase/config.toml.
--
-- Do not add plaintext passwords or direct inserts into public.profiles here.
